# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "src"
out = "build"
libs = ["lib", "node_modules"]
evm_version = "berlin"
gas_reports = ["SLYXToken", "src/StakingverseVault.sol"]
extra_output_files = ["metadata"]
fs_permissions = [
  { access = "read", path = "./scripts/" },
  { access = "read-write", path = "./artifacts/" },
]

# solidity compiler
solc_version = "0.8.22"

# Increase optimizer_runs
optimizer = true
optimizer-runs = 1_000

[fuzz]
# Fuzz more than the default 256
runs = 10000
max_test_rejects = 500000
include_storage = true
include_push_bytes = true
