name: "Build & Tests"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: ❇️ Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: |
          npm ci
          forge install

      - name: ⚒️ Show the Foundry config
        run: |
          forge --version
          forge config

      - name: Build contracts
        id: build
        run: npm run build:sizes

      - name: Run tests
        id: test
        run: npm run test:debug
